name: Publish to Snapcraft

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g., 0.2.7)'
        required: true

concurrency:
  group: snap-${{ inputs.version_name }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preflight | Check release tag
        run: |
          curl -fsSL "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.version_name }}" >/dev/null

      - name: Preflight | Check secret
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        run: |
          [ -n "$SNAPCRAFT_STORE_CREDENTIALS" ] || { echo "Missing secret SNAPCRAFT_TOKEN" >&2; exit 1; }

      - name: Fetch Linux binary (with fallback)
        run: |
          mkdir -p snap/builds
          
          mkdir -p snap/gui
          cp others/flathub/io.github.mlm_games.pomodorot.desktop snap/gui/pomodorot.desktop
          cp icon.png snap/gui/icon.png

          set -e
          echo "Fetch 'pomodorot.x86_64'..."
          curl -fL "https://github.com/${{ github.repository }}/releases/download/${{ inputs.version_name }}/pomodorot.x86_64" -o snap/builds/pomodorot
          chmod +x snap/builds/pomodorot

      - name: Update version in snapcraft.yml
        run: |
          sed -i "s/^version: .*/version: '${{ inputs.version_name }}'/" snap/snapcraft.yaml
          echo "snap/snapcraft.yaml version updated"

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: snap

      - name: Publish to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
